version: PEmo
type: remi
dataset:
  type: PEmo
  feature_path: "./dataset/remi_midi"
  labels: ["HA","LA"]
  cls_type: "A"
  pad_idx: 338
dataloader:
  type: DataLoader
  params:
    batch_size: 16
    num_workers: 8