version: PEmo
type: magenta
dataset:
  type: PEmo
  feature_path: "./dataset/magenta_midi"
  labels: ["Q1","Q2","Q3","Q4"]
  cls_type: "AV"
  pad_idx: 388
dataloader:
  type: DataLoader
  params:
    batch_size: 16
    num_workers: 8