version: PEmo
type: remi
dataset:
  type: PEmo
  feature_path: "./dataset/remi_midi"
  labels: ["Q1","Q2","Q3","Q4"]
  cls_type: "AV"
  pad_idx: 338
dataloader:
  type: DataLoader
  params:
    batch_size: 16
    num_workers: 8