learning_rate: 0.001
momentum: 0.95
weight_decay: 1.0e-05
nesterov: true
mode: min
factor: 0.2
patience: 5
verbose: true
max_epochs: 1000
gpus:
- 0
distributed_backend: dp
benchmark: false
deterministic: true
